/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/menuComponents/about.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADirectoryTree: typeof import('ant-design-vue/es')['DirectoryTree']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATag: typeof import('ant-design-vue/es')['Tag']
    Block: typeof import('./src/components/rightComponents/block.vue')['default']
    Block2: typeof import('./src/components/rightComponents/block2.vue')['default']
    Block3: typeof import('./src/components/rightComponents/block3.vue')['default']
    copy: typeof import('./src/components/rightComponents/block2 copy.vue')['default']
    Favorate: typeof import('./src/components/menuComponents/Favorate.vue')['default']
    Graph: typeof import('./src/components/rightComponents/graph/components/graph.vue')['default']
    Guides: typeof import('./src/components/menuComponents/guides.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    Help: typeof import('./src/components/menuComponents/help.vue')['default']
    Home: typeof import('./src/components/menuComponents/home.vue')['default']
    Home3: typeof import('./src/components/menuComponents/home3.vue')['default']
    Login: typeof import('./src/components/rightComponents/login.vue')['default']
    Menu: typeof import('./src/components/menu.vue')['default']
    Node: typeof import('./src/components/rightComponents/graph/node.vue')['default']
    Rightcontent: typeof import('./src/components/rightcontent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/rightComponents/search.vue')['default']
    Setter: typeof import('./src/components/menuComponents/setter.vue')['default']
    Tcode: typeof import('./src/components/rightComponents/graph/components/Tcode.vue')['default']
    Tgraph: typeof import('./src/components/rightComponents/graph/Tgraph.vue')['default']
    TopBlock: typeof import('./src/components/rightComponents/topBlock.vue')['default']
    Ttable: typeof import('./src/components/rightComponents/graph/components/Ttable.vue')['default']
    Ttext: typeof import('./src/components/rightComponents/graph/components/Ttext.vue')['default']
  }
}
