/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/menuComponents/about.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckableTag: typeof import('ant-design-vue/es')['CheckableTag']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADirectoryTree: typeof import('ant-design-vue/es')['DirectoryTree']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    Block: typeof import('./src/components/rightComponents/block.vue')['default']
    Favorate: typeof import('./src/components/menuComponents/Favorate.vue')['default']
    Graph: typeof import('./src/components/rightComponents/graph.vue')['default']
    Guides: typeof import('./src/components/menuComponents/guides.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    Help: typeof import('./src/components/menuComponents/help.vue')['default']
    Home: typeof import('./src/components/menuComponents/home.vue')['default']
    Home2: typeof import('./src/components/menuComponents/home2.vue')['default']
    Login: typeof import('./src/components/rightComponents/login.vue')['default']
    Menu: typeof import('./src/components/menu.vue')['default']
    Node: typeof import('./src/components/rightComponents/graph/node.vue')['default']
    NodeGraph: typeof import('./src/components/rightComponents/graph/nodeGraph.vue')['default']
    RelationGraph: typeof import('./src/components/rightComponents/relation-graph.vue')['default']
    Rightcontent: typeof import('./src/components/rightcontent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/rightComponents/search.vue')['default']
    Setter: typeof import('./src/components/menuComponents/setter.vue')['default']
  }
}
